SELECT
  se.EVENT_ID,
  se.EVENT_DATE,

  s.NAME,
  s.STATION_ID,
  s.STREAM_TYPE,

  a.ANODE_DIAMETER,
  a.STOCK_DIAMETER,
  a.EQUIPMENT_ID,
  a.ANODE_SHAPE

FROM {0}.WILDADMIN.SamplingEvents_evw as se

INNER JOIN {0}.WILDADMIN.Stations_evw as s
ON s.STATION_ID = se.STATION_ID

INNER JOIN {0}.WILDADMIN.Equipment_evw as e
ON e.EVENT_ID = se.EVENT_ID

INNER JOIN {0}.WILDADMIN.Anodes_evw as a
ON e.EQUIPMENT_ID = a.EQUIPMENT_ID

WHERE se.EVENT_ID IN ({1})
