packages:
  - functions

onlyBuiltDependencies:
  - '@firebase/util'
  - '@vaadin/vaadin-usage-statistics'
  - esbuild
  - protobufjs
  - re2

overrides:
  axios@<1.12.0: '>=1.12.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  on-headers@<1.1.0: '>=1.1.0'
  tmp@<=0.2.3: '>=0.2.4'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
